name: iOS Build

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.12.2'

      - name: Install Dependencies
        run: npm install

      - name: Setup Expo
        run: npm install -g expo-cli

      - name: Build iOS App
        run: |
          expo run:ios

      - name: Upload iOS App
        uses: actions/upload-artifact@v2
        with:
          path: ios/build/Build/Products/Release-iphoneos/mobile-pnb.ipa
